### PR TITLE
Refactor tags command

### PR DESCRIPTION
**Pull request by liuchengxu**
The future plan is to support some features of https://github.com/universal-ctags/citre in vim-clap.

### CODE REVIEW

**Comment by phongnh** [comment]
@liuchengxu because you're working on tags command, could you consider supporting custom/user ctags binary in `proj_tags` provider via settings or provider options? `Clap proj_tags` is using fixed `ctags`:

```vim
let s:support_json_format =
      \ len(filter(systemlist('ctags --list-features'), 'v:val =~# ''^json''')) > 0
```

Thanks.

**Comment by liuchengxu** [comment]
@phongnh Not important for me as it's not hard to inject the binary into the PATH if you already have one, but I'm happy to accept PR.

**Comment by phongnh** [comment]
@liuchengxu You're right. In my machine (Ubuntu), Universal Ctags is installed as `ctags-universal` instead of `ctags`, I'm not sure why (maybe conflicting with Exuberant Ctags). Maybe I just need to build and install Universal Ctags from source instead of package manager. Thanks.

**Comment by romgrk** [comment]
@phongnh Or just create a symlink? Something like ``ln -s `which ctags-universal` /usr/local/bin/ctags``

**Comment by phongnh** [comment]
> @phongnh Or just create a symlink? Something like `` ln -s `which ctags-universal` /usr/local/bin/ctags ``

Thank you @romgrk

**Pull request merged**
