### PR TITLE
Add Solarized themes

### PR DESCRIPTION
**Pull request by jc00ke**
Adding both light and dark.

### CODE REVIEW

**Comment by jc00ke** [comment]
Dark files:
image

Dark search:
image


Light files:
image

Light search:
image

**Comment by liuchengxu** [comment]
Thanks!

**Comment by jc00ke** [comment]
Thank you for your help and the awesome plugin!

**Comment by agriffis** [comment]
Thank you @jc00ke !  I love vim-clap but the colors have always been hard to read for me. I'm not using solarized generally but these themes solve that problem.

**Comment by jc00ke** [comment]
> Thank you @jc00ke ! I love vim-clap but the colors have always been hard to read for me.

What do you think of the dark? It's not quite doing it for me like the light variant is.

**Comment by agriffis** [comment]
> What do you think of the dark? It's not quite doing it for me like the light variant is.

It seems fine to me. I do switch light/dark schemes for day/night, but I'm not sure if I'll switch the vim-clap theme or not. It doesn't matter to me to have the solarized light vim-clap theme on a dark background. It's just nice that it's finally readable.

**Pull request merged**
