### PR TITLE
Add new grep2 provider with cache and dynamic refresh support

### LINKED ISSUE #302: Support dynamic update in maple for grep/files provider
Currently maple only responses when the job is finished, i.e., there is no dynamic update for the time-consuming jobs. We have a spinner in the vim window, that's good, but not perfect. We have introduced a new rpc-based provider in #272, that means all the work required on the vim side has been done, now the job is to implement a dynamic update for running a system command in maple, but it's obviously not easy. It sounds like the core logic of skim without drawing the UI.

1. Start the maple service and run the command on start.
2. User type inside vim.
3. Send the input event to maple via job channel.
4. Response the input event and send back the update periodly.

-------------

- [x] files provider will support dyn filter after #364 is merged.
    - And any provider can benefit from it if the `source` is a String or a function that returns a String.
    - From what I have seen, neovim works great as always with the dyn filter, but vim still behaves bad due to the linewise job invocation. I believe using a timer to reading the output periodly can help, but I'm a neovim user, this timer improvement will be indefinite.
- [ ] new grep2 provider #383, with cache and dynamic refresh support.

### LINKED ISSUE #343: Performance is dramatically bad comparing to fzf.vim
**Environment (please complete the following information):**
 - OS: Macos catalina
 - (Neo)Vim version: nvim 0.4.3
 - vim-clap version: master 5b48e30466517eac6d73bf9cacecfedadda28c5b
 - Have you reproduced with a minimal vimrc: No
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
I know that comparing this plugin to fzf.vim is not very relevant, but just to be more descriprive what would i expect from this plugin :) The problem is - when i typing some text in Clap fzf it loads very slowly and i can see several chars appear at the same time...long story short - here is the video https://share.getcloudapp.com/P8uRk8lB

**Clap debug**

```
            has cargo: 1
            has maple: /Users/alexanderpopov/.config/nvim/plugged/vim-clap/bin/maple
           maple info: version 0.1.8 (git v0.8), built for x86_64-apple-darwin by rustc 1.41.0 (5e1a79984 2020-01-27).

         has +python3: 1
has py dynamic module: 0
     Current FileType: vim
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/alexanderpopov/.config/nvim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_disable_bottom_top = 0
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!'}
    let g:clap_insert_mode_only = v:false
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_search_box_border_style = 'curve'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
    let g:clap_providers_relaunch_code = '@@'
```

**To Reproduce**

1. As a reference you can use my dotfiles - https://github.com/alex-popov-tech/.dotfiles/blob/master/nvim/plugins.vim#L154
2. Try to use `Clap files` or `Clap gfiles`

*Note* - it seems like lags disappear after some quantity of chars

**Expected behavior**
Text should appear in search bar smoothly

**Actual behavior**
While typing text is lagging

**Additional context**
Video - https://share.getcloudapp.com/BluBYnLB

### PR DESCRIPTION
**Pull request by liuchengxu**
Close #302
Close #343

### CODE REVIEW

**Comment by vn-ki** [comment]
How do I use `grep2`?

`Clap grep2` gives. I rebuilt maple from the source. 
```
vim-clap: Fail to load provider: grep2, E:Vim(let):E121: Undefined variable: g:clap#provider#grep2#
```

**Comment by liuchengxu** [comment]
oops, I forgot to commit it :(. Please pull the latest commit @vn-ki

**Comment by vn-ki** [comment]
@liuchengxu `grep2` seems to be matching the filename (unlike `grep`). Is this intentional?

**Comment by vn-ki** [comment]
Also, great job! `grep2` feels much much more responsive than `grep`.

**Comment by liuchengxu** [comment]
That's intentional. I explained a bit about `grep` and `grep2` in CHANGELOG https://github.com/liuchengxu/vim-clap/blob/master/CHANGELOG.md#added .

**Comment by vn-ki** [comment]
It's very annoying, please see this:
`grep2`
image
`grep`
image

Only `grep` provides useful results.

**Comment by vn-ki** [comment]
Can you describe what will be the steps required to achieve grep behaviour in grep2? I will try to implement it.

**Comment by liuchengxu** [comment]
@vn-ki  You write Rust? That's great! Because it has to be done in Rust. I think we could tweak `scorer`, `line` is the raw string that we current filter on, maybe add a converter there, exclude the filename and line number, then we have to handle the offset of matched indices after fuzzy filtering.

https://github.com/liuchengxu/vim-clap/blob/302dd2d7188fc6dff5be9713ac7f0f0ca19fa926/crates/maple_cli/src/cmd/filter/dynamic.rs#L346-L350

```rust
    let scorer = |line: &str| match algo {
        Algo::Skim => {
            // exclude the filename and line number
            let converted_line = convert(line);
            // apply the fuzzy filter on converted line
            let (score, convert_indices) = fuzzy_indices(converted_line, query);

            // handle the offset of convert_indices
            let indices = handle_offset(indices);

            (score, indices)

        }
        Algo::Fzy => match_and_score_with_positions(query, line)
            .map(|(score, indices)| (score as i64, indices)),
    };
```

**Comment by Olical** [comment]
I've noticed that `clap_provider_grep_opts` doesn't seem to apply to `grep2`, might be worth bearing in mind in future changes! It seems to be working for me other than that though!

**Comment by liuchengxu** [comment]
`grep2` works in a different way, see the difference mentioned in CHANGELOG, so the options for `grep` are unapplicable for `grep2`. @Olical

**Comment by liuchengxu** [comment]
@vn-ki  Try #385 .

**Pull request merged**
