### PR TITLE
Show create new file entry when in empty directory

### LINKED ISSUE #591: Filer: show create new file entry when directory is empty
Followup of https://github.com/liuchengxu/vim-clap/issues/589

### PR DESCRIPTION
**Pull request by liuchengxu**
Close #591

cc @phongnh

### CODE REVIEW

**Comment by phongnh** [comment]
@liuchengxu 

I tried to test this PR with minimal vimrc. Here is folder structure

```
.
├── emptydir
├── hello
├── test.txt
└── world

3 directories, 1 file
```

I noticed that I cannot go to folder `emptydir` if I filter with `empty`.

Then, I manually selected `emptydir` and pressed `Tab` to go inside `emptydir`
Typed `test.rb` (this file does not exist), pressed `Enter`, it created `test.rb` buffer
Then I opened `Clap filter` again
Then, I manually selected `emptydir` and pressed `Tab` to go inside `emptydir` again
Typed `hello.rb`, `NO MATCHES FOUND` messages showed instead.

Screenshot from 2021-01-29 00-48-47
Screenshot from 2021-01-29 00-49-15
Screenshot from 2021-01-29 00-49-31
Screenshot from 2021-01-29 00-49-52

**Comment by liuchengxu** [comment]
@phongnh Can not reproduce. Can you share the minmal vimrc and exact steps for the reproduction?

**Comment by liuchengxu** [comment]
@phongnh I can't reproduce the problem you described above, works well for me. I'll merge this PR first and you can post a minimal vimrc and reproduction steps if you still see the problem later.

**Comment by phongnh** [comment]
@liuchengxu okay. Here is my minimal vimrc.

```vimrc
set encoding=utf-8
scriptencoding utf-8
set nocompatible
set termguicolors

set runtimepath^=~/.vim/plugged/vim-clap

syntax on
filetype plugin indent on

```

Also, I used pre-built `maple` with `clap#installer#force_download()` on Linux Pop!OS 20.04.

**Comment by phongnh** [comment]
Here is screencast: https://asciinema.org/a/ybuqXVRScts9ud28KRu6jZOug

**Comment by liuchengxu** [comment]
@phongnh The issue you ran into is not related to this PR, the Lua filter somehow does not work, see `:Clap debug`. If you vim is compiled with Python3 feature, you can use `g:clap_force_python = v:true` or `g:clap_force_matchfuzzy = v:true`.

```vim
set encoding=utf-8
scriptencoding utf-8
set nocompatible
set termguicolors

set runtimepath^=~/.vim/plugged/vim-clap

let g:clap_force_python = v:true

syntax on
filetype plugin indent on
```

**Comment by liuchengxu** [comment]
The no matches found issue has been fixed in https://github.com/liuchengxu/vim-clap/pull/624/commits/10030b864173e9fd3077cad52d02daed62a2bf0d, you can pull the latest commit and try again. @phongnh

**Pull request merged**
