### PR TITLE
fix: resize on neovim

### LINKED ISSUE #516: Neovim redraw “freezes” when clap is enabled
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: Archlinux (5.8.6-arch1-1)
 - (Neo)Vim version:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
```
 - vim-clap version: git commit `973ebcf5411eea777450673b0b3f132beb5004d7`
 - Have you reproduced with a minimal vimrc: no
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes 

**Describe the bug**
Neovim somehow freezes” until I type something, regardless of whether a clap window is open or not (I don’t have that problem if I remove clap from my plugins).

---

Step 1: simply open neovim on a file with another window next to it.

img_090320_124113

Step 2: expand the neovim window and don’t touch anything. You can see a glitched window (half the window is not redrawn).

img_090320_124123

Step 3: type any key (I simply move the cursor). The window gets redrawn completely.

img_090320_124132

**Clap debug**

```
            has cargo: 1
            has maple: /home/phaazon/.config/nvim/plugged/vim-clap/target/release/maple
           maple info: version 0.1.20, built for x86_64-unknown-linux-gnu by rustc 1.45.2 (d3fb005a3 2020-07-31).

         has +python3: 1
has py dynamic module: 1
     Current FileType: toml
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/phaazon/.config/nvim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_current_selection_sign = {'texthl': 'ClapCurrentSelectionSign', 'linehl': 'ClapCurrentSelection', 'text': '->'}
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_fuzzy_match_hl_groups = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    let g:clap_insert_mode_only = v:true
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_selected_sign = {'texthl': 'ClapSelectedSign', 'linehl': 'ClapSelected', 'text': ' ·'}
  Provider Variables:
                     []
```

### PR DESCRIPTION
**Pull request by romgrk**
Closes #516 

Pros:
 - Resizing while clap is closed now works
Cons:
 - Resizing while clap is open now segfaults (neovim bug)

I think it's still preferable to do this, I'm guessing most people don't resize while clap is open.

Source:
```
(gdb) f 4
#4  0x000056238641ce93 in msg_scroll_flush () at ../src/nvim/message.c:2229
2229	    assert(pos_delta >= 0);
```
Known issue: https://github.com/neovim/neovim/issues/12432

### CODE REVIEW

**Comment by romgrk** [comment]
Just thought about this but why don't we just delete code related to resizing windows? I think the use-case is rare enough that it would be ok to just ignore it.

**Comment by liuchengxu** [comment]
> I think the use-case is rare enough that it would be ok to just ignore it.

Yeah, I agree, we can just comment out L82.

https://github.com/liuchengxu/vim-clap/blob/d7bbe7529680662025f633954501a537ba226942/autoload/clap/layout.vim#L81-L83

**Comment by romgrk** [comment]
> just comment out L82

Just comment? I'd delete the unused code, there's not that much of it and I mean one of the powers of git is that we can fearlessly delete code. Checkout the new commit, I'll comment it if you prefer but I would comment directly at the `autocmd VimResized` location, to avoid attaching useless event listeners.

**Review by liuchengxu — APPROVED** [review]
LGTM

**Pull request merged**
