### PR TITLE
Add Solarized Light theme

### PR DESCRIPTION
**Pull request by jc00ke**
Based off of [Solarized Light values](https://github.com/altercation/solarized/tree/62f656a02f93c5190a8753159e34b385588d5ff3/vim-colors-solarized#the-values).

### CODE REVIEW

**Comment by jc00ke** [comment]
`grep` looks fine, though I'm not in love with it:
image

`files` is not right. Thoughts?
image

**Comment by liuchengxu** [comment]
`g:clap_theme` defines the most basic colors, each provider's syntax file can override that, ref: #339.

**Comment by jc00ke** [comment]
> `g:clap_theme` defines the most basic colors, each provider's syntax file can override that, ref: #339.

Thanks, that helped with the fuzzy matches, but I'm still not clear how to override the specific provider colors.

Let's take `files` for example.

```vim
hi TNormal ctermfg=249 ctermbg=NONE guifg=#b2b2b2 guibg=NONE
execute 'syntax match ClapFile' '/^.*/' 'contains='.join(clap#icon#add_head_hl_groups(), ',')

hi default link ClapFile TNormal
```

Would I override `TNormal`?

**Comment by jc00ke** [comment]
@liuchengxu can you help me out with the `TNormal` override? Is that what I'm supposed to be doing, or should I override something else? Thanks!

**Comment by liuchengxu** [comment]
You can define `ClapFile` in `solarized_light.vim` explicitly instead of using the default `TNormal`, e.g.,:

```vim
hi ClapFile ctermfg=170 guifg=#bc6ec5
```

**Comment by jc00ke** [comment]
Closing in favor of #412.

**Pull request closed without merging**
