### PR TITLE
Fix sign group name in vim's popup

### LINKED ISSUE #130: Current line is not highlighed
**Environment (please complete the following information):**
 - OS: windows 10
 - (Neo)Vim version: 8.1.2318
 - vim-clap version: latest master
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
With `C-k` and `C-j` current list item is not visually selected

**To Reproduce**
- Open vim
- Clap files
- `C-j`

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

**Expected behavior**
current line should be highlighted

**Screenshots**
image

### PR DESCRIPTION
**Pull request by arashm**
based on https://github.com/vim/vim/commit/7257073043252c2e01c8e168e6842a1121797243

fixed #130

### CODE REVIEW

**Comment by liuchengxu** [comment]
Thanks for the patch. I'm seeing another issue about the vim sign when playing with #130 on my side. Just want to know if you have the same problem: the sign of the first line shows up when you first enter the input window, but disappears when you input some thing. And then if you navigate between the result list using `<C-k/J>`, the sign show up again.

**Comment by arashm** [comment]
Yes, I do have the same issue. I remember having this issue even before the signs disappeared, so I'm not sure if it's related to #130.

**Comment by liuchengxu** [comment]
I may have figure it out. Can you try if the following patch works for you? If it does, you can put it in your patch and fix the sign problem completely.

```diff
diff --git a/autoload/clap/impl.vim b/autoload/clap/impl.vim
index ecb41f6..31d7f05 100644
--- a/autoload/clap/impl.vim
+++ b/autoload/clap/impl.vim
@@ -90,13 +90,16 @@ function! s:on_typed_sync_impl() abort
   if empty(l:lines)
     let l:lines = [g:clap_no_matches_msg]
     let g:__clap_has_no_matches = v:true
+    call g:clap.display.set_lines_lazy(lines)
+    " In clap#impl#refresh_matches_count() we reset the sign to the first line,
+    " But the signs are seemingly removed when setting the lines, so we should
+    " postpone the sign update.
     call clap#impl#refresh_matches_count('0')
   else
+    call g:clap.display.set_lines_lazy(lines)
     call clap#impl#refresh_matches_count(string(len(l:lines)))
   endif
 
-  call g:clap.display.set_lines_lazy(lines)
-
   call g:clap#display_win.compact_if_undersize()
   call clap#spinner#set_idle()
```

**Comment by arashm** [comment]
Awesome! Looks good to me now.

**Comment by liuchengxu** [comment]
Merged, thanks!

**Pull request merged**
