### PR TITLE
Introduce new rpc-based provider: Clap filer

### LINKED ISSUE #245: Feature request: open file like ivy-mode and findr.vim
I want to find a plugin which can open file in the way of emacs ivy-mode, I found it today, it's name is findr.vim https://github.com/conweller/findr.vim

but, this plugin only works for neovim, it will be wonderful if i can use this funtion in clap. thanks

### PR DESCRIPTION
**Pull request by liuchengxu**
Close #245

clap-filer

### CODE REVIEW

**Comment by hujianxin** [comment]
I tested some cases, that feature works good, thanks.

I found some differences between ivy and clap filer.
1. ivy/helm/findr will use `/` as a trigger to refresh the output
2. ivy/helm/findr will create new file when there's no file matching and user enter `Enter` key.

Maybe these two feature is required most in daily time.

**Comment by liuchengxu** [comment]
>ivy/helm/findr will use / as a trigger to refresh the output

I'm not interested, just use `<Tab>` for expanding the directory.

>ivy/helm/findr will create new file when there's no file matching and user enter Enter key.

This sounds good.

**Comment by hujianxin** [comment]
I thought about it, found `Tab`  can cover most use cases. `Tab` is good

**Comment by hujianxin** [comment]
Ivy/helm will jump to HOME directory when user enter `~/`, is it convenient for vim-clap to achive it?

**Comment by liuchengxu** [comment]
> ivy/helm/findr will create new file when there's no file matching and user enter Enter key.

Done in https://github.com/liuchengxu/vim-clap/pull/272/commits/aff91f8e4d1b398944b1f9e515276f2f53894ff2

> Ivy/helm will jump to HOME directory when user enter ~/, is it convenient for vim-clap to achive it?

Please elaborate.

**Comment by hujianxin** [comment]
> Please elaborate.

😢 I do not know about vimscript, and I try to under your codebase

**Comment by sam-lord** [comment]
> > Ivy/helm will jump to HOME directory when user enter ~/, is it convenient for vim-clap to achive it?
> 
> Please elaborate.

They mean that any directory followed by "~/" will re-write the directory to the current-user's home directory. This is helpful if you run vim in an /etc/ folder and realise you want to be editing a config file in your home dir.

This PR / plugin overall is exactly what I've been looking for, thank you for the work on this!

**Comment by liuchengxu** [comment]
That's a solid use case. I can check if the input ends with `/` and then go to that directory directly. For input like `~/`, it's easy. But there is a problem for input like `/etc`, you want to type `/etc`, but when you input `/`, the hook will be triggered and bring you to `/` directory, that's unexpected.

**Comment by liuchengxu** [comment]
Done in https://github.com/liuchengxu/vim-clap/pull/272/commits/eb5e88f168ee46ae51f3a32b814d92cc538b830f: use `<Tab>` to jump to the directory directly if your input ends with `/`.

I'm not sure whether this PR works as expected on Windows, but if there is no more opinions, I'll merge this soon.

**Pull request merged**
