### PR TITLE
Add preview for files and history provider

### PR DESCRIPTION
**Pull request by liuchengxu**
屏幕快照 2020-02-05 下午9 59 44

### CODE REVIEW

**Comment by skbolton** [comment]
How are you getting the file icons here in the photo?

**Comment by skbolton** [comment]
How are you getting the file icons here in the photo?

**Comment by liuchengxu** [comment]
`:h g:clap_enable_icon`, ensure you have installed the nerdfont https://www.nerdfonts.com/.

**Comment by skbolton** [comment]
Is there any other requirement? I have the setting on and I use nerdfonts in many places in my config. I am not seeing the icons when I do `:Clap files`

**Comment by liuchengxu** [comment]
Do you have installed the rust binary `maple`? `files` icon support is only avaliable when `maple` exists.

**Comment by skbolton** [comment]
Disregard, as soon as I added the installed binary it worked

**Pull request merged**
