### PR TITLE
Introduce g:ClapPrompt for more control of prompt

### LINKED ISSUE #134: Dynamically set the prompt
I want to dynamically set the prompt for each search. Im replicating fzf with source:`fd --type d` sink:`cd`. Then the current dir is shown as prompt in a condensed version.  

Could be a optional provider function `prompt`. I've looked at `g:clap_prompt_format` but that is only sourced once it seems, If that is changed to be checked every time it could be done in `on_enter` I guess?

### PR DESCRIPTION
**Pull request by liuchengxu**
Close #134

### CODE REVIEW

**Comment by meck** [comment]
Great work! I can set the prompt, one issue I tried saving any existing prompt using `on_enter()` and `on_exit()` ie:
``` Vimscript 
function! s:cd.on_enter() abort
  if exists("g:ClapPrompt")
    let s:oldPrompt = g:ClapPrompt
  endif
  let g:ClapPrompt = function('ClapFormat')
endfunction

function! s:cd.on_exit() abort
  if exists("s:oldPrompt")
    let g:ClapPrompt = s:oldPrompt
    unlet s:oldPrompt
  else
    unlet g:ClapPrompt
  endif
endfunction
```

and it seems the prompt is drawn before the call to `on_enter()` I don't know if this is the best way to accomplish this?

**Comment by liuchengxu** [comment]
I think you get confused here. `g:ClapPromt` is a function to generate the prompt when it needs to. You don't have to unlet that. 

```vim
function! s:cd.on_enter() abort
    let s:oldPrompt = clap#spinner#get()
    " Not sure you need to do thing and then call clap#spinner#set(text) here
endfunction

function! s:cd.on_exit() abort
  call clap#spinner#set()
endfunction
```

**Comment by meck** [comment]
Ok, after looking at `spinner.vim` I see, What I am looking to do is to replace the prompt in **one** provider with the `cwd` while keeping the prompt for other providers untouched. 

If I do:
```vim
function! s:cd.on_enter() abort
  call clap#spinner#set('foo')
end-function
```
The prompt resets when typing and also I can't use `%spinner%`.

I wrongly assumed `g:ClapPrompt` was checked for every time the prompt was drawn, but I see its only checked on initial load.

What I was looking for is a per provider `ClapPrompt`, not a global one.

**Comment by liuchengxu** [comment]
>I wrongly assumed g:ClapPrompt was checked for every time the prompt was drawn, but I see its only checked on initial load.

It's indeed initialized only once, but will be evaluated every time the prompt needs to be drawn.

As I have mentioned, being a function `g:ClapPrompt` is able to do anything you want to:

```vim
function! ClapFormat() abort
  " Only use your own format for files provider,
  " otherwise use the default prompt.
  if g:clap.provider.id ==# 'files'
    if exists('g:__clap_provider_cwd')
      let cwd = g:__clap_provider_cwd
    else
      let cwd = getcwd()
    endif
    return '%spinner% '.pathshorten(cwd).':'
  else
    return ' %spinner%%forerunner_status%%provider_id%:'
  endif
endfunction

let g:ClapPrompt = function('ClapFormat')
```

**Comment by meck** [comment]
Thanks for all your help and assistantance! The problem is that I seek to do is, set the prompt from within a provider, without changing anything defined in `.vimrc`. What I tried doing now is something like this:
``` vim
if exists("g:ClapPrompt")
  let s:prevClapPrompt = funcref("g:ClapPrompt")
endif

function! ClapFormat() abort
  if g:clap.provider.id ==# 'cd'
    if exists('g:__clap_provider_cwd')
      let cwd = g:__clap_provider_cwd
    else
      let cwd = getcwd()
    endif
    return '%spinner% '. pathshorten(fnamemodify(expand(cwd), ':~:s?/$??')) . ' '
  elseif exists("s:prevClapPromt")
    call s:prevClapPrompt()
  else
    if exists("g:clap_prompt_format")
      return g:clap.prompt_format
    else
      return ' %spinner%%forerunner_status%%provider_id%:'
    endif
  endif
endfunction

let g:ClapPrompt = function('ClapFormat')
``` 
However that only works if the provider is the first one opened after launch, so `s:PromptFn()` is defined with that one

**Comment by liuchengxu** [comment]
`g:ClapFormat` is a user-level setting, it should not be used like that.

If you want to change the prompt in the provider temporarily, just use `clap#spinner#set(text)` then, the prompt will be reset to the value of `s:PromptFn()` later, or you can use `clap#spinner#refresh()` to reset it to `s:PromptFn()` manually.

**Comment by liuchengxu** [comment]
@meck  I add  a provider level `prompt_format` in #319 and use it for showing the current executive of the tags returned by vista.vim which is changed dynamically. You might want to take a look.

**Pull request merged**
