### PR TITLE
Add separate highlight group for sign column

### PR DESCRIPTION
**Pull request by GoldsteinE**

### CODE REVIEW

**Comment by liuchengxu** [comment]
Thanks for the patch, overall looks ok, but I run into an issue that `ClapSelectedSign` is cleared somehow, not sure what's going on here.

**Comment by GoldsteinE** [comment]
> Thanks for the patch, overall looks ok, but I run into an issue that `ClapSelectedSign` is cleared somehow, not sure what's going on here.

Do you have `g:clap_theme` set? Applying theme seems to clear `ClapSelectedSign` if theme doesn't set it itself.

**Comment by liuchengxu** [comment]
You're right, setting `g:clap_theme` is related.

This patch works for me, can you see if it also works for you?

```diff
diff --git a/autoload/clap/sign.vim b/autoload/clap/sign.vim
index d240df3..a2e7fec 100644
--- a/autoload/clap/sign.vim
+++ b/autoload/clap/sign.vim
@@ -15,12 +15,12 @@ let s:sign_cur_group = 'PopUpClapCurrentSelected'
 if !exists('s:sign_inited')
   call sign_define(s:sign_group, get(g:, 'clap_selected_sign', {
         \ 'text': ' >',
-        \ 'texthl': 'ClapSelectedSign',
+        \ 'texthl': hlexists('ClapSelectedSign') ? 'ClapSelectedSign': 'WarningMsg',
         \ 'linehl': 'ClapSelected'
         \ }))
   call sign_define(s:sign_cur_group, get(g:, 'clap_current_selection_sign', {
         \ 'text': '>>',
-        \ 'texthl': 'ClapCurrentSelectionSign',
+        \ 'texthl': hlexists('ClapCurrentSelectionSign') ? 'ClapCurrentSelectionSign' : 'WarningMsg',
         \ 'linehl': 'ClapCurrentSelection',
         \ }))
   let s:sign_inited = 1
```

**Comment by GoldsteinE** [comment]
Shouldn't it also be done to other highlight groups like `ClapCurrentSelection` in this case?

**Comment by liuchengxu** [comment]
Not sure as only `ClapCurrentSign` and `ClapCurrentSelection` got cleared for me, I actually have no idea why they are cleared.

**Comment by GoldsteinE** [comment]
> Not sure as only `ClapCurrentSign` and `ClapCurrentSelection` got cleared for me

Doesn't your theme set all of other highlights?

**Comment by GoldsteinE** [comment]
UPD: I set theme to completely empty and it doesn't clear highlight for me.

**Comment by liuchengxu** [comment]
The problem is seemingly about setting `g:clap_theme`, not the colorscheme, I personally use https://github.com/liuchengxu/space-vim-theme and also tried https://github.com/joshdick/onedark.vim, they are clear as long as I set `g:clap_theme`

min.rc:

```vim
set nocompatible

set runtimepath^=~/.vim/plugged/vim-clap/
set runtimepath^=~/.vim/plugged/space-vim-theme/
set runtimepath^=~/.vim/plugged/onedark.vim

syntax on
filetype plugin indent on

set termguicolors

"color space_vim_theme
color onedark

let g:clap_theme = 'material_design_dark'
```
1. `:Clap`.
2. `:hi ClapCurrentSelectionSign`, you'll see it's cleared.

**Comment by GoldsteinE** [comment]
Can't reproduce with this config:
image
Can you reproduce this without `space-vim-theme`? Maybe it somehow breaks this?

**Comment by liuchengxu** [comment]
onedark alao happens this issue:

```vim
set nocompatible

set runtimepath^=~/.vim/plugged/vim-clap/
set runtimepath^=~/.vim/plugged/onedark.vim

syntax on
filetype plugin indent on

set termguicolors

color onedark

let g:clap_theme = 'material_design_dark'
```

I believe there are more colorschemes that can have this problem.

**Comment by GoldsteinE** [comment]
Ok, I cloned both `onedark` and `space-vim-theme` and started Vim with exactly same config. `ClapCurrentSelectionSign` is still linked to `WarningMsg` for me in both NeoVim 0.5.0 and Vim 8.2 (patches 1-148).

**Comment by liuchengxu** [comment]
That's so weired, I'm using vim8.2.1-205 and NVIM v0.5.0-nightly-1153-gab860cb5f. Also tried your https://github.com/GoldsteinE/vim-atom-dark:

屏幕快照 2020-02-06 下午10 21 52

**Comment by GoldsteinE** [comment]
Are you sure you are using latest `vim-clap` from my branch? I re-cloned `vim-clap`:
```
$ git clone git@github.com:GoldsteinE/vim-clap.git
Cloning into 'vim-clap'...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 2373 (delta 22), reused 36 (delta 16), pack-reused 2311
Receiving objects: 100% (2373/2373), 748.37 KiB | 2.01 MiB/s, done.
Resolving deltas: 100% (1469/1469), done.
$ cd vim-clap
$ git checkout sign-highlight
Branch 'sign-highlight' set up to track remote branch 'sign-highlight' from 'origin'.
Switched to a new branch 'sign-highlight'
$ git pull
Already up to date.
$ git reset --hard origin/sign-highlight
HEAD is now at 09b75c2 Add keys for signs highlight groups to themes.vim
```
And it works for me in that state.

**Comment by GoldsteinE** [comment]
Also if it still doesn't work for you after re-cloning, can you please tell me if highlight group is cleared with this config?
```vim
set nocompatible
set runtimepath^=~/.vim/plugged/vim-clap/
syntax on
filetype plugin on
set termguicolors
let g:clap_theme = 'material_design_dark'
```

**Comment by liuchengxu** [comment]
Ok, I was using the old version of your patch. With the latest pull, it works now.

**Comment by GoldsteinE** [comment]
Oh, it's cool, I was already thinking we're going to debug Vim itself. :)
Is there anything else that prevents this PR from merging?

**Comment by liuchengxu** [comment]
Merged, thanks!

**Pull request merged**
