### PR TITLE
Don't match filepath in grep2

### PR DESCRIPTION
**Pull request by liuchengxu**
Fix https://github.com/liuchengxu/vim-clap/pull/383#issuecomment-611453184

Also fix some errors found in maple.

### CODE REVIEW

**Comment by vn-ki** [comment]
Yes, this work!

I found more problems with grep2 though.

image
image

As you can see fuzzy is given more preference in grep2 than letter case. I find this behaviour very weird.

**Comment by vn-ki** [comment]
See how the result changes when one extra letter is added,

image
image

**Comment by liuchengxu** [comment]
Just like what I have mentioned in https://github.com/liuchengxu/vim-clap/blob/master/CHANGELOG.md#added, that's expected at the moment, for `grep2` is forced to use the fzy fuzzy algorigthm, but `grep` is not, which returns the result of ripgrep directly. We could apply the search syntax of `grep` to `grep2` later, but for now, that's how `grep2` works.

**Comment by liuchengxu** [comment]
@vn-ki  Can you show me the link of the repo used in your above picture?

**Comment by vn-ki** [comment]
https://github.com/vn-ki/harsark.rs

I find fuzzy really unsuitable for text searching.

image
image

**Comment by liuchengxu** [comment]
@vn-ki You just spot a bug of clap! This patch should help at present.

```diff
diff --git a/autoload/clap/filter/async/dyn.vim b/autoload/clap/filter/async/dyn.vim
index 66b043b..6e3e732 100644
--- a/autoload/clap/filter/async/dyn.vim
+++ b/autoload/clap/filter/async/dyn.vim
@@ -30,7 +30,7 @@ function! clap#filter#async#dyn#from_tempfile(tempfile) abort
   else
     let enable_icon_opt = ''
   endif
-  let filter_cmd = printf('%s --number 100 --winwidth %d filter "%s" --input "%s"',
+  let filter_cmd = printf('%s --number 30 --winwidth %d filter "%s" --input "%s"',
         \ enable_icon_opt,
         \ winwidth(g:clap.display.winid),
         \ g:clap.input.get(),
@@ -41,7 +41,7 @@ endfunction
 
 function! clap#filter#async#dyn#start_grep() abort
   let s:last_query = g:clap.input.get()
-  let grep_cmd = printf('%s --number 100 --winwidth %d grep "" "%s" --cmd-dir "%s"',
+  let grep_cmd = printf('%s --number 30 --winwidth %d grep "" "%s" --cmd-dir "%s"',
         \ g:clap_enable_icon ? '--enable-icon' : '',
         \ winwidth(g:clap.display.winid),
         \ g:clap.input.get(),
@@ -53,7 +53,7 @@ endfunction
 
 function! clap#filter#async#dyn#grep_from_cache(tempfile) abort
   let s:last_query = g:clap.input.get()
-  let grep_cmd = printf('%s %s --number 100 --winwidth %d grep "" "%s" --input "%s"',
+  let grep_cmd = printf('%s %s --number 30 --winwidth %d grep "" "%s" --input "%s"',
         \ g:clap_enable_icon ? '--enable-icon' : '',
         \ has_key(g:clap.context, 'no-cache') ? '--no-cache' : '',
         \ winwidth(g:clap.display.winid),
```

截屏2020-04-10 上午12 46 36

**Comment by liuchengxu** [comment]
@vn-ki  The issue you found should be fixed on mater now. The future improvements could be to add new filter approach aside from the current fuzzy filter ways, e.g, plain string match. https://github.com/junegunn/fzf#search-syntax is also nice to have, but it might need quite a work.

**Comment by liuchengxu** [comment]
@vn-ki Another dyn filter bug has been fixed, now the filtered results should be right https://github.com/liuchengxu/vim-clap/commit/e53d3c16c44f047db8e5a7be519015574327458f , I was wondering why some entries are not put on the top.

**Pull request merged**
